gon/basic/urls.py
from django.conf.urls import url 
from basic import views

app_name='basic'
urlpatterns = [
    url(r'^register/$' , views.register , name='register'),
    url(r'^userlogin/$' , views.user_login , name='login'),

]

gon/gon/urls.py
from django.conf.urls import url,include
from basic import views
from django.contrib import admin

urlpatterns = [
    url(r'^$' , views.index , name="index"),
    url(r'^basic_app/' , include('basic.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$' , views.user_logout , name='logout'),
]

gon/basic/models.py
from django.db import models
from django.contrib.auth.models import User

class Userprofileinfo(models.Model):

    user = models.OneToOneField(User)


    porfolio_sit = models.URLField(blank = True)
    profile_pic=models.ImageField(upload_to='profile_pics' , blank=True)


    def __str__(self):
        return self.user.username
# Create your models here.

gon/basic/forms.py
from django import forms
from django.contrib.auth.models import User
from basic.models import Userprofileinfo

class Userform(forms.ModelForm):

    password = forms.CharField(widget= forms.PasswordInput())

    class Meta():
        model= User
        fields= ('username', 'email', 'password')



class Userprofileform(forms.ModelForm):
    class Meta():
        model = Userprofileinfo
        fields= ('porfolio_sit', 'profile_pic')

gon/basic/views.py
from django.shortcuts import render
from django.http import HttpResponse
from basic.models import Userprofileinfo , User
from basic.forms import Userform , Userprofileform
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse , HttpResponseRedirect
from django.contrib.auth import authenticate , login , logout
# Create your views here.
def index(request):
    return render(request , 'basic_app/index.html')

def register(request):

    registered = False

    if request.method =='POST':

        user_form= Userform(data=request.POST)
        profile_form = Userprofileform(data= request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()


            profile = profile_form.save(commit =False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
               

            profile.save()

            registered=True

        else:
            print(user_form.errors , profile_form.errors)
    
    else:
        user_form = Userform
        profile_form = Userprofileform

    



    return render(request , 'basic_app/register.html', {'user_form':user_form ,
 'profile_form':profile_form  , 'registered':registered})



def user_login(request):
    if request.method == 'POST':
        
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active :

                login(request , user)
                return HttpResponseRedirect(reverse('index'))
            
            else:
                return HttpResponse('not active')
        
        else: 
            print('some one tried and failed to log in')
            return HttpResponse('invalid')
    else:
        return render(request , 'basic_app/login.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

gon/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

</head>
<body>
   

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
          <a class="navbar-brand" href="{% url 'index' %}">Home</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'basic:register' %}">Register <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
              </li>

              
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link " href="{% url 'logout' %}">Logout</a>
              </li>

              {% else %}

              <li class="nav-item">
                <a class="nav-link " href="{% url 'basic:login' %}">Login</a>
              </li>
              {% endif %}
                
             
            </ul>
          </div>
      </div>
        </nav>

  <div class="container">
    {% block body_block %}
        


    {% endblock  %}
         
</div>
</body>
</html>

gon/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
<div class="jumbotron">

<h1>Django level 5</h1>

</div>

{% endblock  %}

gon/templates/basic_app/login.html
{% extends "basic_app/base.html" %}


{% block body_block %}
    

<div class="jumbotron">

    <h1>please login over here</h1>

    <form action="{% url 'basic:login' %}" method="POST">


        {% csrf_token %}
        <input type="text" name="username" id="" placeholder="username">

        <input type="text" name="password" id="Password">

        <input type="submit" name="" id="" value="Login">
    </form>
</div>
{% endblock  %}
    

gon/templates/basic_app/register.html
{% extends "basic_app/base.html" %}


{% block body_block %}
{% if registered %}
<h1>Thanks</h1>

{% else %}
<h3>register over here bud</h3>
<div class="jumbotron">
<form enctype="multipart/form-data" method="POST">

    {% csrf_token %}
    {{user_form.as_p}}
    {{profile_form.as_p}}

    <input type="submit" name="" id="" value="Register">

</form>
</div>
{% endif %}

{% endblock %}